# -*- coding: utf-8 -*-
"""Week_01_Practice_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXBikDsPwR18adIyFsHX9VqY4qFiBU5Q

# Session 01: Ungraded Practice Assignment
Welcome to your first practice assignment! This notebook covers the basics of Google Colab, arithmetic, data types and variables.
**Instructions:**
*   Write your Python code in the empty code cells below each question.
*   To run a code cell, click the "Play" button on the left or press `Shift + Enter`.
*   *Note: This is an ungraded practice assignment and doesn't need to be submitted anywhere.*

## Part 1: Arithmetic & Comparison Operators

**Question 1:**
Perform the following arithmetic operations in the code cell below:
1. Multiply 15 by 4.
2. Subtract 12 from the result.
3. Divide the final number by 3.

*Leave your final division expression on the last line to see the output. Notice how division always returns a Float!*
"""

(15*4-12)/3

"""**Question 2:**
Write an expression that checks if `45 * 3` is greater than or equal to `120`.
*(It should return a Boolean: True or False)*
"""

45*3>=120

"""## Part 2: Working with Strings

**Question 3:**
Python allows you to create strings in a few different ways.
1. Create a variable called `first_name` and assign it your first name using single quotes.
2. Create a variable called `last_name` and assign it your last name using double quotes.
3. Create a variable called `bio` and assign it a multi-line string using the appropriate quote marks.
4. Place the `bio` variable on the last line to see how Colab displays multi-line text.
"""

first_name = 'Amandeep'
last_name = 'Mani'
bio = 'I am a student and studing in CSJMU'
bio

"""## Part 3: Variables & Assignment Operators

**Question 4:**
Variables allow us to store data dynamically.
1. Create a variable named `score` and assign it the value `50`.
2. On the next line, reassign the `score` variable to be `100`.
3. Check if your current `score` is not equal to  `50`. *italicized text*
"""

score = 50
score = 100
score != 50

"""## Part 4: Reassigning Variables & Comparison

**Question 5:**
Variables can be overwritten. Let's test this along with comparing values.
1. Create a variable called `current_year` and set it to 2023.
2. On the very next line, overwrite `current_year` so it now holds the value 2024.
3. On the last line, write an expression to check if `current_year` is strictly *not equal* to 2023.
"""

current_year = 2023
current_year = 2024
current_year != 2023